let shopItemsData = [
  {
    id: 'a',
    img: 'img/2.jpg',
    name: 'Platinum Watch',
    price: '59',
  },
  {
    id: 'b',
    img: 'img/3.jpg',
    name: 'Moonstone Watch',
    price: '59',
  },
  {
    id: 'c',
    img: 'img/6.jpg',
    name: 'Leather Boots',
    price: '105',
  },
  {
    id: 'd',
    img: 'img/7.jpg',
    name: 'Leopard Loafers',
    price: '105',
  },
  {
    id: 'e',
    img: 'img/8.jpg',
    name: 'Sports Shoes',
    price: '105',
  },
  {
    id: 'f',
    img: 'img/24.jpg',
    name: 'White T-shirt',
    price: '45',
  },
  {
    id: 'g',
    img: 'img/25.jpg',
    name: 'Red T-shirt',
    price: '45',
  },
  {
    id: 'h',
    img: 'img/26.jpg',
    name: 'ArmyGreen T-shirt',
    price: '45',
  },
  {
    id: 'i',
    img: 'img/9.webp',
    name: 'Purple Gown',
    price: '237',
  },
  {
    id: 'j',
    img: 'img/10.webp',
    name: 'Saree',
    price: '149',
  },
  {
    id: 'k',
    img: 'img/11.jpg',
    name: 'Cowboy Hat',
    price: '27',
  },
  {
    id: 'l',
    img: 'img/12.jpg',
    name: 'Winter Cap',
    price: '15',
  },
  {
    id: 'm',
    img: 'img/13.jpg',
    name: 'School Backpack',
    price: '65',
  },
  {
    id: 'n',
    img: 'img/1.webp',
    name: 'Wedding Gown',
    price: '365',
  },
  {
    id: 'o',
    img: 'img/4.jpg',
    name: 'Pearl Necklace',
    price: '489',
  },
  {
    id: 'p',
    img: 'img/5.jpg',
    name: 'Gold Rings',
    price: '299',
  },
]
